/** Every visible string of the Channels panel, as μClient's world-panels/copy.ts `channels` had them. Sentence case; CSS uppercases. */
export const COPY = {
  title: 'Channels',
  awaiting: 'Waiting for channels',
  none: 'No channels',
  noMessages: 'No messages yet',
  noChannel: 'No channel.',
  placeholder: (ch: string) => `message ${ch}`,
  settings: 'Settings',
  settingsTitle: 'channel settings',
  muted: 'Muted',
  mute: 'Mute', unmute: 'Unmute', muteTitle: 'mute channel',
  alerts: 'Alerts',
  alertAll: 'Every message',
  alertMentions: 'Mentions only',
  alertNone: 'None',
  online: (n: number) => `${n} online`,
  unread: (n: number) => `${n} unread`,
  rail: 'Channels',
  color: 'Colour',
  colorDefault: 'default',
  colors: { accent: 'accent', 'accent-bright': 'bright accent', gold: 'gold', alert: 'alert', ok: 'ok', fg: 'text', 'fg-dim': 'dim text' } as Record<string, string>,
  search: 'Search',
  searchTitle: 'search this channel',
  searchPlaceholder: 'search channel',
  noMatch: 'no match',
  badRegex: 'not a valid regex',
  prev: 'previous', next: 'next', close: 'close',
  prevLabel: 'Prev', nextLabel: 'Next', closeLabel: 'Close',
  popOut: 'Pop out',
  popOutTitle: (ch: string) => `pop out ${ch}`,
  soloTitle: (ch: string) => `Channel · ${ch}`,
  gone: (ch: string) => `channel ${ch} is not open here`,
};
